ALTER TABLE channels ADD COLUMN public_id uuid NOT NULL DEFAULT gen_random_uuid(), ADD COLUMN phone_number_id text, ADD COLUMN business_account_id text, ADD COLUMN credentials_encrypted text, ADD COLUMN verify_token_hash text, ADD COLUMN last_webhook_at timestamptz, ADD COLUMN last_successful_message_at timestamptz, ADD COLUMN last_error_at timestamptz, ADD COLUMN last_error_code text;
CREATE UNIQUE INDEX channels_public_id_uq ON channels(public_id);
ALTER TABLE contacts ADD COLUMN display_name text, ADD COLUMN profile_picture_url text, ADD COLUMN language text, ADD COLUMN country text;
ALTER TABLE conversations ADD COLUMN last_message_id uuid, ADD COLUMN customer_service_window_expires_at timestamptz;
CREATE UNIQUE INDEX conversations_active_identity_uq ON conversations(organization_id,channel_id,contact_id,status);
ALTER TABLE messages ADD COLUMN channel_id uuid REFERENCES channels(id), ADD COLUMN contact_id uuid REFERENCES contacts(id), ADD COLUMN provider_reply_to_message_id text, ADD COLUMN reply_to_message_id uuid, ADD COLUMN type text NOT NULL DEFAULT 'text', ADD COLUMN provider_timestamp timestamptz, ADD COLUMN error_code text, ADD COLUMN error_message text, ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}';
UPDATE messages m SET channel_id=c.channel_id,contact_id=c.contact_id FROM conversations c WHERE m.conversation_id=c.id;
DROP INDEX IF EXISTS messages_provider_id_uq;
CREATE UNIQUE INDEX messages_channel_provider_id_uq ON messages(channel_id,provider_message_id);
ALTER TABLE outbox_jobs RENAME COLUMN kind TO job_type;
ALTER TABLE outbox_jobs RENAME COLUMN attempts TO attempt_count;
ALTER TABLE outbox_jobs ADD COLUMN aggregate_type text NOT NULL DEFAULT 'message', ADD COLUMN max_attempts integer NOT NULL DEFAULT 5, ADD COLUMN locked_at timestamptz, ADD COLUMN locked_by text, ADD COLUMN last_error text, ADD COLUMN completed_at timestamptz;
CREATE INDEX outbox_org_status_idx ON outbox_jobs(organization_id,status);
CREATE TABLE provider_webhook_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,channel_id uuid REFERENCES channels(id) ON DELETE CASCADE,provider text NOT NULL,provider_event_key text NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,signature_valid boolean NOT NULL,status text NOT NULL DEFAULT 'pending',attempt_count integer NOT NULL DEFAULT 0,last_error text,received_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX webhook_provider_event_uq ON provider_webhook_events(provider,provider_event_key);
CREATE INDEX webhook_status_idx ON provider_webhook_events(status,received_at);
CREATE TABLE message_status_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,provider_message_id text,status message_status NOT NULL,provider_timestamp timestamptz,payload jsonb NOT NULL DEFAULT '{}',event_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX message_status_event_key_uq ON message_status_events(event_key);
CREATE TABLE message_flow_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,message_id uuid REFERENCES messages(id) ON DELETE CASCADE,trace_id uuid NOT NULL,event_type text NOT NULL,source text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX message_flow_trace_idx ON message_flow_events(trace_id);
CREATE INDEX message_flow_message_idx ON message_flow_events(message_id,created_at);
